language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install -r audio/requirements.txt"
  - "pip install -r ibm_cloud_functions/requirements.txt"
  - "pip install flake8"
script:
 - flake8 . --ignore E501,F841